### register user
POST http://localhost:8080/register
Content-Type: application/json

{
  "name": "test1",
  "email": "test1@mail.com",
  "mobileNumber": "1234567890",
  "pwd": "123",
  "role": "user"
}